<?php

namespace Database\Seeders;

use App\Domain\Product\Models\Category;
use Illuminate\Database\Seeder;

class ProductCategorySeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            ['id' => 1, 'name' => 'Electronics', 'name_ar' => 'إلكترونيات', 'name_en' => 'Electronics', 'slug' => 'electronics', 'description' => 'Devices, accessories, and smart gadgets for daily use.', 'icon_url' => 'categories/1/icon/MhWk41cuGwBOBLFADCvsPQdMyhowxPJ3vIz5Gcdr.png', 'parent_id' => null, 'sort_order' => 1, 'is_active' => true, 'created_at' => '2026-05-02 18:51:07', 'updated_at' => '2026-05-05 16:29:45'],
            ['id' => 2, 'name' => 'Smartphones', 'name_ar' => 'هواتف ذكية', 'name_en' => 'Smartphones', 'slug' => 'smartphones', 'description' => 'Smartphones offers and curated product selections.', 'icon_url' => 'categories/2/icon/9GPc0RRFYN3fweSLyYJBNChcobrlgelCsxdEJjtV.png', 'parent_id' => 1, 'sort_order' => 2, 'is_active' => true, 'created_at' => '2026-05-02 18:51:07', 'updated_at' => '2026-05-05 16:40:09'],
            ['id' => 4, 'name' => 'Audio', 'name_ar' => 'صوتيات', 'name_en' => 'Audio', 'slug' => 'audio', 'description' => 'Audio offers and curated product selections.', 'icon_url' => 'categories/4/icon/lrwJgEtVgz4sZas5H6VJ70WgodwV4dImCRJc6Di1.png', 'parent_id' => 1, 'sort_order' => 4, 'is_active' => true, 'created_at' => '2026-05-02 18:51:07', 'updated_at' => '2026-05-07 13:11:53'],
            ['id' => 5, 'name' => 'Fashion', 'name_ar' => 'أزياء', 'name_en' => 'Fashion', 'slug' => 'fashion', 'description' => 'Clothing, footwear, and accessories for every season.', 'icon_url' => 'categories/5/icon/nkL2S5Z7UYZj7aywp1Q1F2ExzGut09VgeosP1Hlg.jpg', 'parent_id' => null, 'sort_order' => 5, 'is_active' => true, 'created_at' => '2026-05-02 18:51:07', 'updated_at' => '2026-05-02 18:51:07'],
            ['id' => 6, 'name' => 'Men Fashion', 'name_ar' => 'أزياء رجالية', 'name_en' => 'Men Fashion', 'slug' => 'men-fashion', 'description' => 'Men Fashion offers and curated product selections.', 'icon_url' => 'categories/6/icon/bjLUMro16rm1PqBafSejsJLHjWQyZ5rPTNdTIlxx.png', 'parent_id' => 5, 'sort_order' => 6, 'is_active' => true, 'created_at' => '2026-05-02 18:51:07', 'updated_at' => '2026-05-02 18:51:07'],
            ['id' => 7, 'name' => 'Women Fashion', 'name_ar' => 'أزياء نسائية', 'name_en' => 'Women Fashion', 'slug' => 'women-fashion', 'description' => 'Women Fashion offers and curated product selections.', 'icon_url' => 'categories/7/icon/4aRO5m8VOUhRwrjnFGrzkoHYTf1AuuJw32SJ0sdk.png', 'parent_id' => 5, 'sort_order' => 7, 'is_active' => true, 'created_at' => '2026-05-02 18:51:07', 'updated_at' => '2026-05-02 18:51:07'],
            ['id' => 8, 'name' => 'Footwear', 'name_ar' => 'أحذية', 'name_en' => 'Footwear', 'slug' => 'footwear', 'description' => 'Footwear offers and curated product selections.', 'icon_url' => 'categories/8/icon/iJoBIT1VjfZ3IsktQoYtvOxrmE6o31fyctHWxeVo.png', 'parent_id' => 5, 'sort_order' => 8, 'is_active' => true, 'created_at' => '2026-05-02 18:51:07', 'updated_at' => '2026-05-02 18:51:07'],
            ['id' => 9, 'name' => 'Food & Beverages', 'name_ar' => 'أطعمة ومشروبات', 'name_en' => 'Food & Beverages', 'slug' => 'food-beverages', 'description' => 'Meal deals, grocery bundles, and cafe offers.', 'icon_url' => 'categories/9/icon/DhPFcXZrkVlJ93E6B2EboEbj3ilpWdjHhHTTMg00.jpg', 'parent_id' => null, 'sort_order' => 9, 'is_active' => true, 'created_at' => '2026-05-02 18:51:07', 'updated_at' => '2026-05-02 18:51:07'],
            ['id' => 10, 'name' => 'Restaurant Deals', 'name_ar' => 'عروض المطاعم', 'name_en' => 'Restaurant Deals', 'slug' => 'restaurant-deals', 'description' => 'Restaurant Deals offers and curated product selections.', 'icon_url' => 'categories/10/icon/OnxHD1EQVYTMvMSsblSqTFdZwswoVHbw3bQQ5olM.jpg', 'parent_id' => 9, 'sort_order' => 10, 'is_active' => true, 'created_at' => '2026-05-02 18:51:07', 'updated_at' => '2026-05-02 18:51:07'],
            ['id' => 11, 'name' => 'Grocery Bundles', 'name_ar' => 'باقات البقالة', 'name_en' => 'Grocery Bundles', 'slug' => 'grocery-bundles', 'description' => 'Grocery Bundles offers and curated product selections.', 'icon_url' => 'categories/11/icon/knKvYYpCsOYFJdanguATrJZh516HmuR3aSBxRzAL.jpg', 'parent_id' => 9, 'sort_order' => 11, 'is_active' => true, 'created_at' => '2026-05-02 18:51:07', 'updated_at' => '2026-05-02 18:51:07'],
            ['id' => 12, 'name' => 'Coffee & Desserts', 'name_ar' => 'قهوة وحلويات', 'name_en' => 'Coffee & Desserts', 'slug' => 'coffee-desserts', 'description' => 'Coffee & Desserts offers and curated product selections.', 'icon_url' => 'categories/12/icon/0nf1lrvXIfQsU1CotDU8Bg5Xscql5GgmhdRlIfuk.png', 'parent_id' => 9, 'sort_order' => 12, 'is_active' => true, 'created_at' => '2026-05-02 18:51:07', 'updated_at' => '2026-05-02 18:51:07'],
            ['id' => 13, 'name' => 'Home & Garden', 'name_ar' => 'المنزل والحديقة', 'name_en' => 'Home & Garden', 'slug' => 'home-garden', 'description' => 'Home essentials, decor, and practical upgrades.', 'icon_url' => 'categories/13/icon/jQBAIeT5clMLO1b9maaI0AJEwGcEjbxu5YaDjBez.webp', 'parent_id' => null, 'sort_order' => 13, 'is_active' => true, 'created_at' => '2026-05-02 18:51:07', 'updated_at' => '2026-05-02 18:51:07'],
            ['id' => 14, 'name' => 'Home Decor', 'name_ar' => 'ديكور المنزل', 'name_en' => 'Home Decor', 'slug' => 'home-decor', 'description' => 'Home Decor offers and curated product selections.', 'icon_url' => 'categories/14/icon/19h9PYdcJluHXiuJCoLIpnw1ILKNU0bX70mebnNG.png', 'parent_id' => 13, 'sort_order' => 14, 'is_active' => true, 'created_at' => '2026-05-02 18:51:07', 'updated_at' => '2026-05-02 18:51:07'],
            ['id' => 15, 'name' => 'Kitchen Essentials', 'name_ar' => 'أساسيات المطبخ', 'name_en' => 'Kitchen Essentials', 'slug' => 'kitchen-essentials', 'description' => 'Kitchen Essentials offers and curated product selections.', 'icon_url' => 'categories/15/icon/lRBi8vlJQteq7t0toPX0qPzgbZpiiyZs8vzkZwQp.webp', 'parent_id' => 13, 'sort_order' => 15, 'is_active' => true, 'created_at' => '2026-05-02 18:51:07', 'updated_at' => '2026-05-02 18:51:07'],
            ['id' => 16, 'name' => 'Beauty & Health', 'name_ar' => 'الجمال والصحة', 'name_en' => 'Beauty & Health', 'slug' => 'beauty-health', 'description' => 'Self-care products, skincare, and wellness bundles.', 'icon_url' => 'categories/16/icon/evRBaMyZ6Rf8ytSPv0uWfTkJB4DtQuzxV6WtNSZR.jpg', 'parent_id' => null, 'sort_order' => 16, 'is_active' => true, 'created_at' => '2026-05-02 18:51:07', 'updated_at' => '2026-05-02 18:51:07'],
            ['id' => 17, 'name' => 'Skincare', 'name_ar' => 'العناية بالبشرة', 'name_en' => 'Skincare', 'slug' => 'skincare', 'description' => 'Skincare offers and curated product selections.', 'icon_url' => 'categories/17/icon/sG888r4bzDwLziCSXM1lVIU28DpxpGurYp2nzf6X.png', 'parent_id' => 16, 'sort_order' => 17, 'is_active' => true, 'created_at' => '2026-05-02 18:51:07', 'updated_at' => '2026-05-02 18:51:07'],
            ['id' => 18, 'name' => 'Wellness', 'name_ar' => 'العناية الصحية', 'name_en' => 'Wellness', 'slug' => 'wellness', 'description' => 'Wellness offers and curated product selections.', 'icon_url' => null, 'parent_id' => 16, 'sort_order' => 52, 'is_active' => true, 'created_at' => '2026-05-02 18:51:07', 'updated_at' => '2026-05-02 18:51:07'],
            ['id' => 19, 'name' => 'Sports & Outdoors', 'name_ar' => 'الرياضة والأنشطة الخارجية', 'name_en' => 'Sports & Outdoors', 'slug' => 'sports-outdoors', 'description' => 'Fitness, outdoor gear, and active lifestyle products.', 'icon_url' => 'categories/19/icon/Dc1MM9m6FvZJAeNtE2BI5bGfOySq8HRyCpAyRtdG.png', 'parent_id' => null, 'sort_order' => 19, 'is_active' => true, 'created_at' => '2026-05-02 18:51:07', 'updated_at' => '2026-05-02 18:51:07'],
            ['id' => 20, 'name' => 'Fitness Gear', 'name_ar' => 'معدات اللياقة', 'name_en' => 'Fitness Gear', 'slug' => 'fitness-gear', 'description' => 'Fitness Gear offers and curated product selections.', 'icon_url' => 'categories/20/icon/8S1bWmGEW5zvx90p9crrTNTDyiqVSbv6Artq4MSs.png', 'parent_id' => 19, 'sort_order' => 20, 'is_active' => true, 'created_at' => '2026-05-02 18:51:07', 'updated_at' => '2026-05-02 18:51:07'],
            ['id' => 21, 'name' => 'Cycling', 'name_ar' => 'الدراجات', 'name_en' => 'Cycling', 'slug' => 'cycling', 'description' => 'Cycling offers and curated product selections.', 'icon_url' => null, 'parent_id' => 19, 'sort_order' => 62, 'is_active' => true, 'created_at' => '2026-05-02 18:51:07', 'updated_at' => '2026-05-02 18:51:07'],
            ['id' => 22, 'name' => 'Flights and Travel', 'name_ar' => 'رحلات وسفر', 'name_en' => 'Flights and Travel', 'slug' => 'flights-and-travel', 'description' => null, 'icon_url' => 'categories/22/icon/YnuGkon7ZEofsiHSCQgSR9eLzSpXKUNbRvzPm46K.png', 'parent_id' => null, 'sort_order' => 0, 'is_active' => true, 'created_at' => '2026-06-30 20:22:23', 'updated_at' => '2026-06-30 20:22:23'],
            ['id' => 23, 'name' => 'Inside Egypt', 'name_ar' => 'داخل مصر', 'name_en' => 'Inside Egypt', 'slug' => 'inside-egypt', 'description' => null, 'icon_url' => null, 'parent_id' => 22, 'sort_order' => 0, 'is_active' => true, 'created_at' => '2026-06-30 20:24:59', 'updated_at' => '2026-06-30 20:24:59'],
            ['id' => 24, 'name' => 'Outside Egypt', 'name_ar' => 'خارج مصر', 'name_en' => 'Outside Egypt', 'slug' => 'outside-egypt', 'description' => null, 'icon_url' => null, 'parent_id' => 22, 'sort_order' => 0, 'is_active' => true, 'created_at' => '2026-06-30 20:26:00', 'updated_at' => '2026-06-30 20:26:00'],
        ];

        foreach ($categories as $category) {
            Category::query()->updateOrCreate(
                ['id' => $category['id']],
                $category
            );
        }

        $this->command->info(count($categories).' product categories seeded from export');
    }
}
